### ISSUE TITLE
Open the file how ?

### ISSUE THREAD

**Issue by spotanjo3** [hippie68/psxitarch-how-to#1]
> We also need to change pacman's repo. Open the file /etc/pacman.conf and change the very last line,
> 
> Server = https://psxita.it/repo
> to
> 
> Server = https://psxita.it/repo-testing
> 

How do I do that.. Open the file in PS4. How ?

**Comment by hippie68** [comment]
Like this:

    sudo nano /etc/pacman.conf

Then change the line, and exit and save by pressing "CTRL-x" and confirm with "y".

I will change that part to make it more clear.

**Comment by spotanjo3** [comment]
Thank you!
