### ISSUE TITLE
Why 1 GB and why not 3GB?

### ISSUE THREAD

**Issue by spotanjo3** [hippie68/psxitarch-how-to#2]
`Select the payload "Linux (1 GB)", as it is important not to select "Linux (3 GB)" for the first-time setup, and wait for the jailbreak to succeed`

If 1Gb is necessarily then can you change it to 3GB after the first-time setup? If so, how ?

**Comment by hippie68** [comment]
After psxitarch.tar.xz has been installed, you can use the jailbreak website to load the "Linux (3 GB)" payload the next time you boot the PS4.

**Comment by spotanjo3** [comment]
> After psxitarch.tar.xz has been installed, you can use the jailbreak website to load the "Linux (3 GB)" payload the next time you boot the PS4.

Awesome. I didn't know that. Thanks! Closed now.
