### ISSUE TITLE
Usb ports crashing

### ISSUE THREAD

**Issue by tottia6** [hippie68/psxitarch-how-to#7]
Hi,

I have this issue on my cuh 2216a that after ~20 mins the usb ports crash and will not come back. I have tried both kernels (4.14 and 5.3.7) and result is the same. Fedora, gentoo, arch, on every distro the issue is the same. Things that I've also tried:
-loading 1g and 3g payloads
-loading payload with and without usb devices plugged in
-diffrent order of the usb devices on my usb hub (Trust halyx)
-tried 4g swapfile
-lower fan threshold temp
-internal hdd installation

My usb flash drive: sandisk ultra 64g
Firmware: 7.55
So here are all the things I have tried but any suggestions are very welcome!

**Comment by hippie68** [comment]
You could try entering "dmesg -w" to see live information about USB devices. Perhaps it helps to find the cause. It could very well be the USB hub not being properly supported by Linux. I have a USB hub that works perfectly well on Windows, but keeps disconnecting over and over on Linux, which dmesg shows in detail.

**Comment by tottia6** [comment]
Thanks, gonna try that. And yes, the compatible os for the usb hub is only windows macos and chrome os.
