### ISSUE TITLE
question about image size

### ISSUE THREAD

**Issue by gabriel-maxx** [hippie68/psxitarch-how-to#9]
hello I would like to know why the size of this updated version is 1.72gb, and the original is 2.6gb almost 1gb of difference, what has changed? this is normal?

**Comment by hippie68** [comment]
I cleared the package cache, which resulted in the smaller size. It is referred to at the end of the how-to's update section (step 6).
https://wiki.archlinux.org/title/pacman#Cleaning_the_package_cache

**Comment by gabriel-maxx** [comment]
@hippie68 thanks
